TagFamily : tag16h5
ImagePath : tag_image/
ImageCount : 30
GenTags : [0, 1, 2]
GenPath : gen_tags/

0 :
  File : tag16h5_0.png
  Size : 100
  Canvas : [1000, 1000]
  Extand_Dot :
    - [400, 0, 50]
    - [0, 400, 50]
    - [-400, 0, 50]
    - [0, -400, 50]
  Pixpermm : 10
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
1 :
  File : tag16h5_1.png
  Size : 100
  Canvas : [600, 1000]
  Extand_Dot :
    - [200, 0, 20]
    - [0, 400, 40]
    - [-200, 0, 20]
    - [0, -400, 40]
  Pixpermm : 5
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
2 :
  File : tag16h5_2.png
  Size : 100
  Canvas : [600, 600]
  Extand_Dot :
    - [200, 200, 20]
    - [-200, -200, 20]
    - [-200, 200, 20]
    - [200, -200, 20]
  Pixpermm : 2
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]

ImageTopic : /camera/color/image_raw
ImageSize : [1280, 720]
ImageIntrinsic : [920.251953125, 0.0, 650.4122924804688, 0.0, 921.1195678710938, 355.5172424316406, 0.0, 0.0, 1.0]
ImageDistrotion : [0.0, 0.0, 0.0, 0.0, 0.0] # k1 k2 p1 p2 k3
T_b_c :
  - [1, 0, 0, 0]
  - [0, 1, 0, 0]
  - [0, 0, 1, 0]
  - [0, 0, 0, 1]
PosePublishTopic : /Pose
